--- #YAML:1.0
name:               PDL-DSP-Fir
version:            0.004
abstract:           Finite impulse response filter kernels.
author:
    - John Lapeyre <jlapeyre@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PDL:                0
    PDL::DSP::Windows:  0
    Test::More:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
